server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true #是否从eurkaserver抓取已有的注册信息默认为true 单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

feign:
  hystrix:
    enabled: true
