server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-service #微服务名称


eureka:
  client:
    register-with-eureka: true #表示将自己注册到EurkaServer 默认true
    fetch-registry: true #是否从eurkaserver抓取已有的注册信息默认为true 单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
        defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka



